### ISSUE TITLE
Update 3d viewer to latest node-ports

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-services#92]
@pcrespov commented on [Thu Mar 04 2021](https://github.com/ITISFoundation/cookiecutter-osparc-service/issues/41)

We would like to include the 3D viewer in the list of dispatch able viewers for VTK but needs some features only available in the latest version of node-ports. Could you please update node_ports, release to everybody and let us know so we can add it to the list?
thx

**Comment by odeimaiz** [comment]
The feature needed in the node-ports is the download link support.
